// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WebsiteImagesScraper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("imageCount")]
        public long ImageCount { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("maxLinksReached")]
        public bool MaxLinksReached { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("external")]
        public bool External { get; set; }

        [JsonProperty("src")]
        public Uri Src { get; set; }
    }
}
