// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WebsiteImagesScraper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("imageCount")]
        public long? ImageCount { get; set; }

        [JsonProperty("externalImageCount")]
        public long? ExternalImageCount { get; set; }

        [JsonProperty("internalImageCount")]
        public long? InternalImageCount { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("uniqueDomains")]
        public object[] UniqueDomains { get; set; }

        [JsonProperty("maxLinksReached")]
        public bool? MaxLinksReached { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("src")]
        public Uri Src { get; set; }

        [JsonProperty("external")]
        public bool? External { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
